export const SEARCH_QUERY_ACTION = 'SEARCH_QUERY_ACTION';
export const SEARCH_QUERY_ACTION_SUCCESS = 'SEARCH_QUERY_ACTION_SUCCESS';
export const SEARCH_QUERY_ACTION_FAILURE = 'SEARCH_QUERY_ACTION_FAILURE';