export const SEARCH_QUERY_ACTION = 'SEARCH_QUERY_ACTION';
export const SEARCH_QUERY_ACTION_SUCCESS = 'SEARCH_QUERY_ACTION_SUCCESS';
export const SEARCH_QUERY_ACTION_FAILURE = 'SEARCH_QUERY_ACTION_FAILURE';
export const SEARCH_QUERY_PARAMETER = 'SEARCH_QUERY_PARAMETER';

export const FETCH_WEATHER_ACTION = 'FETCH_WEATHER_ACTION';
export const FETCH_WEATHER_SUCCESS = 'FETCH_WEATHER_SUCCESS';
export const FETCH_WEATHER_FAILURE = 'FETCH_WEATHER_FAILURE';
export const FETCH_WEATHER_FORECAST = 'FETCH_WEATHER_FORECAST';